import type { DocumentProcessor, DocumentRegistry } from '../../../core/document-engine/registry/documentRegistry';
import type { File } from '../../../core/document-engine/types/File';
import type { DocxToTxtResult } from './DocxToTxtResult';
import { asOutput, caught, failed, isDocxArchive, mammothWarnings, outputName, readFile, sourceOf } from '../shared';
import { validateDocxFile } from '../shared';
function htmlToText(html: string): string { const root = new DOMParser().parseFromString(`<body>${html}</body>`, 'text/html').body; const block = 'ADDRESS,ARTICLE,ASIDE,BLOCKQUOTE,DIV,DL,DT,DD,FIGCAPTION,FIGURE,FOOTER,FORM,H1,H2,H3,H4,H5,H6,HEADER,HR,LI,MAIN,NAV,OL,P,PRE,SECTION,TABLE,TBODY,TD,TFOOT,TH,THEAD,TR,UL'; const lines: string[] = []; const visit = (node: Node): void => { if (node.nodeType === Node.TEXT_NODE) { const text = node.textContent?.replace(/\s+/g, ' ') ?? ''; if (text) lines.push(text); return; } if (node.nodeType !== Node.ELEMENT_NODE) return; const element = node as Element; const start = lines.length; element.childNodes.forEach(visit); if (element.matches(block) && lines.length > start) lines.push('\n'); }; root.childNodes.forEach(visit); return lines.join('').replace(/[ \t]+\n/g, '\n').replace(/\n[ \t]+/g, '\n').replace(/\n{3,}/g, '\n\n').trim(); }
export class DocxToTxtProcessor implements DocumentProcessor<DocxToTxtResult> { type = 'docx' as const; async process(file: File | readonly File[], rawOptions: Record<string, unknown> = {}): Promise<DocxToTxtResult> { if (!('size' in file)) return failed({ name: '', size: 0 }, 'DOCX_FILE_REQUIRED', 'A single DOCX file is required'); const source = sourceOf(file); const invalid = validateDocxFile(file); if (invalid.length) return failed(source, 'INVALID_DOCX', invalid.join('. ')); try { const data = await readFile(file); if (!isDocxArchive(data)) return failed(source, 'CORRUPT_DOCX', 'The file is not a valid DOCX archive'); const mammoth = await import('mammoth'); const converted = await mammoth.convertToHtml({ arrayBuffer: data }); const warnings = mammothWarnings(converted.messages); const text = htmlToText(converted.value); if (!text) return failed(source, 'EMPTY_DOCUMENT', 'The DOCX contains no printable content', warnings); const options = rawOptions as { filename?: string }; const blob = new Blob([text], { type: 'text/plain' }); return { success: true, source, outputSize: blob.size, output: asOutput(outputName(file.name, 'txt', options.filename), blob, 'text/plain', { characterCount: text.length }), warnings, errors: [], metadata: { characterCount: text.length } }; } catch (error) { return caught(source, 'DOCX_TO_TXT_FAILED', error); } } }
export const docxToTxtProcessor = new DocxToTxtProcessor();
export function registerDocxToTxtProcessor(registry: DocumentRegistry): DocxToTxtProcessor { if (!registry.getAll(docxToTxtProcessor.type).includes(docxToTxtProcessor)) registry.register(docxToTxtProcessor); return docxToTxtProcessor; }
