import type { File } from '../../../core/document-engine/types/File';
import { asOutput, isDocxArchive, mammothWarnings, outputName, readFile } from './docxHelpers';
import { isReadableFile, validateDocxFile } from './wordValidator';
import type { WordResult, WordWarning } from './wordTypes';
import { caught, failed, wordWarning } from './wordErrors';
import { sourceOf } from './wordTypes';

export const RTF_TYPE = 'application/rtf';
export const ODT_TYPE = 'application/vnd.oasis.opendocument.text';
const MAX_ARCHIVE_ENTRIES = 5000;

export function escapeXml(value: string): string { return value.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;').replace(/'/g, '&apos;'); }
export function escapeRtf(value: string): string { return value.replace(/\\/g, '\\\\').replace(/[{}]/g, '\\$&').replace(/[^\x20-\x7e]/g, (character) => `\\u${character.charCodeAt(0)}?`); }

export async function docxHtml(file: File): Promise<{ html: string; warnings: WordWarning[]; data: ArrayBuffer } | WordResult> {
  const source = sourceOf(file); const invalid = validateDocxFile(file); if (invalid.length) return failed(source, 'INVALID_DOCX', invalid.join('. '));
  try { const data = await readFile(file); if (!isDocxArchive(data)) return failed(source, 'CORRUPT_DOCX', 'The file is not a valid DOCX archive'); const converted = await (await import('mammoth')).convertToHtml({ arrayBuffer: data }); const warnings = mammothWarnings(converted.messages); if (!converted.value.trim()) return failed(source, 'EMPTY_DOCUMENT', 'The DOCX contains no printable content', warnings); return { html: converted.value, warnings, data }; } catch (error) { return caught(source, 'DOCX_READ_FAILED', error); }
}

function htmlRoot(html: string): HTMLElement { return new DOMParser().parseFromString(`<body>${html}</body>`, 'text/html').body; }
function rtfInline(element: Element): string { return Array.from(element.childNodes).map((node) => { if (node.nodeType === Node.TEXT_NODE) return escapeRtf(node.textContent ?? ''); if (node.nodeType !== Node.ELEMENT_NODE) return ''; const child = node as Element; const text = rtfInline(child); const tag = child.tagName.toLowerCase(); const prefix = tag === 'b' || tag === 'strong' ? '\\b ' : tag === 'i' || tag === 'em' ? '\\i ' : tag === 'u' ? '\\ul ' : ''; const suffix = tag === 'b' || tag === 'strong' ? '\\b0 ' : tag === 'i' || tag === 'em' ? '\\i0 ' : tag === 'u' ? '\\ul0 ' : ''; return prefix + text + suffix; }).join(''); }

export function htmlToRtf(html: string): { text: string; warnings: WordWarning[] } {
  const root = htmlRoot(html); const warnings: WordWarning[] = []; const blocks: string[] = [];
  const visit = (element: Element, list?: 'bullet' | 'number') => { const tag = element.tagName.toLowerCase(); if (tag === 'ul' || tag === 'ol') { Array.from(element.children).forEach((child) => visit(child, tag === 'ul' ? 'bullet' : 'number')); return; } if (tag === 'table') { Array.from(element.querySelectorAll(':scope > tbody > tr, :scope > tr')).forEach((row) => blocks.push(`\\trowd ${Array.from(row.children).map((cell) => `${rtfInline(cell)}\\cell`).join('')}\\row`)); return; } if (/^h[1-6]$/.test(tag)) blocks.push(`\\b ${rtfInline(element)}\\b0\\par`); else if (['p', 'div', 'li', 'pre', 'blockquote'].includes(tag)) blocks.push(`${list ? `\\pntext ${list === 'bullet' ? '\\u8226?' : ''} ` : ''}${rtfInline(element)}\\par`); else Array.from(element.children).forEach((child) => visit(child)); };
  Array.from(root.children).forEach((element) => visit(element)); if (root.querySelector('img,video,iframe,svg')) warnings.push(wordWarning('FIDELITY_LIMITED', 'Images and interactive media are not represented in RTF output.')); return { text: `{\\rtf1\\ansi\\deff0\n${blocks.join('\n')}}`, warnings };
}

export function rtfToHtml(input: string): { html: string; warnings: WordWarning[] } {
  if (!/^\s*\{\\rtf[0-9]/i.test(input)) throw new Error('The input is not an RTF document');
  if (input.length > 25 * 1024 * 1024) throw new Error('RTF input exceeds the size limit');
  let depth = 0; let output = ''; let bold = false; let italic = false; let underline = false; const warnings: WordWarning[] = []; const stack: Array<[boolean, boolean, boolean]> = [];
  const flush = (value: string) => { if (!value) return; const text = value.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;'); output += `${bold ? '<strong>' : ''}${italic ? '<em>' : ''}${underline ? '<u>' : ''}${text}${underline ? '</u>' : ''}${italic ? '</em>' : ''}${bold ? '</strong>' : ''}`; };
  for (let index = 0; index < input.length;) { const character = input[index]; if (character === '{') { if (++depth > 100) throw new Error('RTF group nesting is too deep'); stack.push([bold, italic, underline]); index++; continue; } if (character === '}') { if (!depth--) throw new Error('Unbalanced RTF group'); [bold, italic, underline] = stack.pop() ?? [false, false, false]; index++; continue; } if (character !== '\\') { const end = input.slice(index).search(/[\\{}]/); const stop = end < 0 ? input.length : index + end; flush(input.slice(index, stop).replace(/\r?\n/g, '')); index = stop; continue; } const rest = input.slice(index + 1); const hex = /^'([0-9a-f]{2})/i.exec(rest); if (hex) { flush(String.fromCharCode(parseInt(hex[1], 16))); index += 4; continue; } const control = /^([a-z]+)(-?\d+)? ?/i.exec(rest); if (!control) { if ('\\{}'.includes(rest[0])) flush(rest[0]); index += 2; continue; } const word = control[1].toLowerCase(); const value = control[2] ? Number(control[2]) : undefined; index += control[0].length + 1; if (word === 'b') bold = value !== 0; else if (word === 'i') italic = value !== 0; else if (word === 'ul') underline = value !== 0; else if (word === 'par' || word === 'line') output += '<br>'; else if (word === 'tab') flush('\t'); else if (word === 'u' && value !== undefined) flush(String.fromCharCode(value < 0 ? value + 65536 : value)); else if (!['rtf', 'ansi', 'deff', 'fonttbl', 'colortbl', 'viewkind', 'uc', 'f', 'fs', 'pard', 'plain', 'ql', 'qr', 'qc', 'qj', 'li', 'fi', 'tx', 'sa', 'sb', 'lang'].includes(word)) warnings.push(wordWarning('UNSUPPORTED_RTF_CONTROL', `Unsupported RTF control word \\${word} was ignored.`)); }
  if (depth !== 0) throw new Error('Unbalanced RTF groups'); if (!output.replace(/<[^>]+>/g, '').trim()) throw new Error('The RTF document is empty'); return { html: `<p>${output.replace(/(?:<br>){2,}/g, '</p><p>')}</p>`, warnings };
}

function odtContent(html: string): { xml: string; warnings: WordWarning[] } { const root = htmlRoot(html); const warnings: WordWarning[] = []; const inline = (element: Element): string => Array.from(element.childNodes).map((node) => node.nodeType === Node.TEXT_NODE ? escapeXml(node.textContent ?? '') : node.nodeType === Node.ELEMENT_NODE ? `<text:span text:style-name="${/^(b|strong)$/i.test((node as Element).tagName) ? 'T-Bold' : /^(i|em)$/i.test((node as Element).tagName) ? 'T-Italic' : /^u$/i.test((node as Element).tagName) ? 'T-Underline' : 'T-Text'}">${inline(node as Element)}</text:span>` : '').join(''); const blocks: string[] = []; Array.from(root.children).forEach((element) => { const tag = element.tagName.toLowerCase(); if (tag === 'ul' || tag === 'ol') blocks.push(`<text:list text:style-name="${tag === 'ul' ? 'L-Bullet' : 'L-Number'}">${Array.from(element.children).map((item) => `<text:list-item><text:p>${inline(item)}</text:p></text:list-item>`).join('')}</text:list>`); else if (tag === 'table') blocks.push(`<table:table table:name="Table1">${Array.from(element.querySelectorAll(':scope > tbody > tr, :scope > tr')).map((row) => `<table:table-row>${Array.from(row.children).map((cell) => `<table:table-cell><text:p>${inline(cell)}</text:p></table:table-cell>`).join('')}</table:table-row>`).join('')}</table:table>`); else if (/^h[1-6]$/.test(tag)) blocks.push(`<text:h text:outline-level="${tag[1]}">${inline(element)}</text:h>`); else if (['p', 'div', 'li', 'pre', 'blockquote'].includes(tag)) blocks.push(`<text:p>${inline(element)}</text:p>`); }); if (root.querySelector('img,video,iframe,svg')) warnings.push(wordWarning('FIDELITY_LIMITED', 'Images and unsupported media were omitted from ODT output.')); return { xml: blocks.join(''), warnings }; }

export async function htmlToOdt(html: string): Promise<{ blob: Blob; warnings: WordWarning[] }> { const content = odtContent(html); const JSZip = (await import('jszip')).default; const zip = new JSZip(); zip.file('mimetype', ODT_TYPE, { compression: 'STORE' }); zip.file('META-INF/manifest.xml', `<?xml version="1.0"?><manifest:manifest xmlns:manifest="urn:oasis:names:tc:opendocument:xmlns:manifest:1.0" manifest:version="1.2"><manifest:file-entry manifest:media-type="${ODT_TYPE}" manifest:full-path="/"/><manifest:file-entry manifest:media-type="text/xml" manifest:full-path="content.xml"/></manifest:manifest>`); zip.file('content.xml', `<?xml version="1.0"?><office:document-content xmlns:office="urn:oasis:names:tc:opendocument:xmlns:office:1.0" xmlns:text="urn:oasis:names:tc:opendocument:xmlns:text:1.0" xmlns:style="urn:oasis:names:tc:opendocument:xmlns:style:1.0" xmlns:table="urn:oasis:names:tc:opendocument:xmlns:table:1.0"><office:body><office:text>${content.xml}</office:text></office:body></office:document-content>`); zip.file('styles.xml', '<?xml version="1.0"?><office:document-styles xmlns:office="urn:oasis:names:tc:opendocument:xmlns:office:1.0"><office:styles/></office:document-styles>'); zip.file('meta.xml', '<?xml version="1.0"?><office:document-meta xmlns:office="urn:oasis:names:tc:opendocument:xmlns:office:1.0"><office:meta/></office:document-meta>'); return { blob: await zip.generateAsync({ type: 'blob', mimeType: ODT_TYPE }), warnings: content.warnings }; }

export async function odtHtml(file: File): Promise<{ html: string; warnings: WordWarning[] } | WordResult> { const source = sourceOf(file); if (!isReadableFile(file) || !/\.odt$/i.test(file.name) || file.size <= 0) return failed(source, 'INVALID_ODT', 'A readable, non-empty ODT file is required'); try { const zip = await (await import('jszip')).default.loadAsync(await readFile(file)); if (Object.keys(zip.files).length > MAX_ARCHIVE_ENTRIES) return failed(source, 'ODT_TOO_MANY_ENTRIES', 'The ODT archive contains too many entries'); if ((await zip.file('mimetype')?.async('string'))?.trim() !== ODT_TYPE) return failed(source, 'INVALID_ODT', 'The archive is not a valid ODT package'); const content = await zip.file('content.xml')?.async('string'); if (!content) return failed(source, 'INVALID_ODT', 'The ODT package has no content.xml'); const doc = new DOMParser().parseFromString(content, 'application/xml'); if (doc.querySelector('parsererror')) return failed(source, 'CORRUPT_ODT', 'The ODT content.xml is not valid XML'); const text = doc.getElementsByTagName('office:text')[0]; const warnings: WordWarning[] = []; const html = Array.from(text?.children ?? []).map((node) => { const tag = node.localName; if (tag === 'h') { const level = node.getAttribute('text:outline-level') ?? '1'; return `<h${level}>${escapeXml(node.textContent ?? '')}</h${level}>`; } if (tag === 'p') return `<p>${escapeXml(node.textContent ?? '')}</p>`; if (tag === 'list') return `<ul>${Array.from(node.children).map((item) => `<li>${escapeXml(item.textContent ?? '')}</li>`).join('')}</ul>`; warnings.push(wordWarning('UNSUPPORTED_ODT_FEATURE', `ODT element ${tag} was simplified.`)); return ''; }).join(''); return html.trim() ? { html, warnings } : failed(source, 'EMPTY_DOCUMENT', 'The ODT contains no printable content'); } catch (error) { return caught(source, 'ODT_READ_FAILED', error); } }

export async function htmlToDocx(html: string): Promise<Blob> { const api = await import('docx'); const root = htmlRoot(html); const runs = (node: Node, bold = false, italics = false, underline = false): any[] => { if (node.nodeType === Node.TEXT_NODE) return node.textContent ? [new api.TextRun({ text: node.textContent, bold, italics, underline: underline ? {} : undefined })] : []; if (node.nodeType !== Node.ELEMENT_NODE) return []; const element = node as Element; return Array.from(element.childNodes).flatMap((child) => runs(child, bold || /^(B|STRONG)$/i.test(element.tagName), italics || /^(I|EM)$/i.test(element.tagName), underline || /^U$/i.test(element.tagName))); }; const children: any[] = []; Array.from(root.children).forEach((element) => { const tag = element.tagName.toLowerCase(); if (tag === 'table') { const rows = Array.from(element.querySelectorAll(':scope > tbody > tr, :scope > tr')).map((row) => new api.TableRow({ children: Array.from(row.children).map((cell) => new api.TableCell({ children: [new api.Paragraph({ children: runs(cell) })] })) })); if (rows.length) children.push(new api.Table({ rows })); return; } if (tag === 'ul' || tag === 'ol') { Array.from(element.children).forEach((item) => children.push(new api.Paragraph({ children: runs(item), numbering: { reference: tag === 'ol' ? 'batch-numbered' : 'batch-bulleted', level: 0 } }))); return; } children.push(new api.Paragraph({ children: runs(element), heading: /^h([1-6])$/i.test(tag) ? api.HeadingLevel[`HEADING_${tag[1]}` as keyof typeof api.HeadingLevel] : undefined })); }); const numbering = { config: [{ reference: 'batch-bulleted', levels: [{ level: 0, format: api.LevelFormat.BULLET, text: '\\u2022', alignment: api.AlignmentType.LEFT }] }, { reference: 'batch-numbered', levels: [{ level: 0, format: api.LevelFormat.DECIMAL, text: '%1.', alignment: api.AlignmentType.LEFT }] }] }; return api.Packer.toBlob(new api.Document({ numbering, sections: [{ properties: {}, children }] })); }