import { PlatformTaskPage } from '@/components/PlatformTaskPage';
import { FormatToPdfInterface, type FormatToPdfMode } from '@/components/FormatToPdfInterface';
import { getAllPlatformToolByRoute } from '@/tools/platform/allTools';

const content: Record<FormatToPdfMode,{details:Array<{title:string;text:string}>;faq:Array<{question:string;answer:string}>}> = {
  'jpg-to-pdf': { details:[{title:'One image per page',text:'Each JPG or JPEG is embedded into its own PDF page in the selected order.'},{title:'Control page layout',text:'Choose A4 or Letter, portrait or landscape, and contain or cover fitting.'},{title:'Browser conversion',text:'The images are embedded into a new PDF without requiring a document account.'}], faq:[{question:'Can I combine several JPGs into one PDF?',answer:'Yes. Select multiple JPG or JPEG files and arrange them in the order you want before conversion.'},{question:'Can I choose A4 or Letter pages?',answer:'Yes. Both page sizes and portrait or landscape orientation are available.'},{question:'Does the converter change my original images?',answer:'No. It creates a new PDF and leaves the selected image files unchanged.'}] },
  'png-to-pdf': { details:[{title:'Combine PNG pages',text:'Select one or more PNG images and convert them into a single ordered PDF.'},{title:'Handle transparency',text:'PNG transparency is retained where supported while the PDF page background remains predictable.'},{title:'Flexible page layout',text:'Choose page size, orientation, and image fitting before creating the PDF.'}], faq:[{question:'Can I convert PNG to PDF online?',answer:'Yes. Select one or more PNG images and download a new PDF created in the browser.'},{question:'Can several PNG files become one PDF?',answer:'Yes. Every selected PNG becomes one page in the output PDF.'},{question:'Can I reorder the images?',answer:'Yes. Use the up and down controls before conversion.'}] },
  'html-to-pdf': { details:[{title:'Upload or paste HTML',text:'Choose an HTML file or paste markup directly into the browser editor.'},{title:'Sanitize before rendering',text:'Scripts, embeds, forms, unsafe event handlers, and remote resources are removed before PDF rendering.'},{title:'Choose PDF layout',text:'Render to A4 or Letter in portrait or landscape orientation.'}], faq:[{question:'Can I paste HTML instead of uploading a file?',answer:'Yes. Pasted HTML markup can be converted directly.'},{question:'Does HTML to PDF run JavaScript?',answer:'No. Unsafe scripts and executable markup are removed before rendering.'},{question:'Will remote images and styles load?',answer:'Remote resources are intentionally restricted; self-contained HTML with embedded or inline content is the most reliable input.'}] },
  'excel-to-pdf': { details:[{title:'Read XLSX workbooks',text:'The browser reads the workbook and converts each selected workbook sheet into HTML for PDF rendering.'},{title:'Render every sheet',text:'The default workflow includes all workbook sheets in their existing order.'},{title:'Choose page orientation',text:'Use portrait or landscape A4 or Letter pages for the generated PDF.'}], faq:[{question:'Can I convert Excel to PDF online?',answer:'Yes. The current converter supports XLSX workbooks and renders their sheets into a downloadable PDF.'},{question:'Does it support old XLS files?',answer:'The current production interface is limited to XLSX. It does not claim legacy XLS support until that format is validated.'},{question:'Are formulas recalculated?',answer:'The converter reads workbook content through the XLSX engine; it is not a full Microsoft Excel calculation runtime.'}] },
};

export function FormatToPdfPage({route,mode}:{route:string;mode:FormatToPdfMode}){const tool=getAllPlatformToolByRoute(route);if(!tool)throw new Error(`Unknown converter route: ${route}`);const page=content[mode];return <PlatformTaskPage route={route} title={tool.title} description={tool.description} tool={<FormatToPdfInterface mode={mode} toolId={tool.id}/>} details={page.details} faq={page.faq}/>;}
