import { PlatformTaskPage } from '@/components/PlatformTaskPage';
import { PdfPageOperationInterface, type PdfPageOperationMode } from '@/components/PdfPageOperationInterface';
import { getAllPlatformToolByRoute } from '@/tools/platform/allTools';

const content: Record<PdfPageOperationMode,{details:Array<{title:string;text:string}>;faq:Array<{question:string;answer:string}>}> = {
  'rotate-pdf': { details:[{title:'Rotate all or selected pages',text:'Use all for the whole document or enter individual pages and ranges.'},{title:'Three rotation choices',text:'Rotate selected pages 90, 180, or 270 degrees clockwise.'},{title:'Create a new PDF',text:'The original file stays unchanged and the rotated version downloads separately.'}], faq:[{question:'Can I rotate only one PDF page?',answer:'Yes. Enter a single page number, such as 2, before running the rotation.'},{question:'Can I rotate all pages at once?',answer:'Yes. Leave the page field as all.'},{question:'Does the tool change my original PDF?',answer:'No. It creates a new rotated PDF.'}] },
  'delete-pdf-pages': { details:[{title:'Choose pages to remove',text:'Enter individual pages or ranges such as 2,4-6.'},{title:'Keep at least one page',text:'The tool prevents deletion of every page so the output remains a valid document.'},{title:'Download a clean copy',text:'A new PDF is created containing only the pages you kept.'}], faq:[{question:'How do I delete pages from a PDF?',answer:'Choose the PDF, enter the pages you want to remove, then select Delete pages.'},{question:'Can I delete several page ranges?',answer:'Yes. Combine individual pages and ranges with commas, for example 2,4-6,9.'},{question:'Can I delete every page?',answer:'No. At least one page must remain in the output PDF.'}] },
  'extract-pdf-pages': { details:[{title:'Select the pages you need',text:'Enter one or more pages or ranges to keep in the extracted copy.'},{title:'Preserve your chosen sequence',text:'Selected pages are copied to a new PDF in the order you enter them.'},{title:'Original stays intact',text:'Extraction creates a separate file and does not modify the source PDF.'}], faq:[{question:'Can I save only certain PDF pages?',answer:'Yes. Enter the page numbers or ranges you want and download them as a new PDF.'},{question:'Can I extract non-consecutive pages?',answer:'Yes. A selection such as 1,4,8-10 is supported.'},{question:'Does extracting pages delete them from the original?',answer:'No. The original PDF is unchanged.'}] },
  'organize-pdf': { details:[{title:'See the complete page sequence',text:'After upload the current order is filled in automatically.'},{title:'Enter a new order',text:'Rearrange the comma-separated page sequence so every source page appears exactly once.'},{title:'Download the reordered PDF',text:'The processor rebuilds the document in your specified page order.'}], faq:[{question:'How do I reorder PDF pages?',answer:'Upload the PDF, edit the page sequence to the order you want, then choose Reorder pages.'},{question:'Can I leave a page out?',answer:'Not in Organize PDF. This tool expects every page exactly once. Use Extract PDF Pages if you want only a subset.'},{question:'Can I duplicate a page?',answer:'The organize workflow intentionally requires every original page exactly once.'}] },
};

export function PdfPageOperationPage({route,mode}:{route:string;mode:PdfPageOperationMode}){const tool=getAllPlatformToolByRoute(route);if(!tool)throw new Error(`Unknown PDF page tool route: ${route}`);const page=content[mode];return <PlatformTaskPage route={route} title={tool.title} description={tool.description} tool={<PdfPageOperationInterface mode={mode} toolId={tool.id}/>} details={page.details} faq={page.faq}/>;}
