import type { PlatformToolDefinition } from './catalog';

export const liveCreatorTools: readonly PlatformToolDefinition[] = [
  { id:'resume-maker', route:'/resume-maker', name:'Resume Maker', title:'Resume Maker – Create a Resume Online', description:'Build a clean professional resume with a live preview, then download it as DOCX, PDF, or TXT.', eyebrow:'RESUME MAKER', primaryIntent:'Create a resume online', kind:'creator', cluster:'Document Creator', priority:'P2', stage:'Research First', secondaryKeywords:['resume builder online','create resume online','resume maker'], input:['Form fields'], output:['DOCX','PDF','TXT'], processor:'creator-studio', launchState:'live', indexable:true },
  { id:'cover-letter-maker', route:'/cover-letter-maker', name:'Cover Letter Maker', title:'Cover Letter Maker – Create a Cover Letter Online', description:'Create a focused cover letter for a role with live preview and DOCX, PDF, or TXT download.', eyebrow:'COVER LETTER MAKER', primaryIntent:'Create a cover letter online', kind:'creator', cluster:'Document Creator', priority:'P2', stage:'Research First', secondaryKeywords:['cover letter builder','cover letter generator online','make cover letter'], input:['Form fields'], output:['DOCX','PDF','TXT'], processor:'creator-studio', launchState:'live', indexable:true },
  { id:'write-letter-online', route:'/write-letter-online', name:'Letter Writer Online', title:'Write a Letter Online – Free Letter Writer', description:'Draft a structured formal or personal letter in your browser and export it as DOCX, PDF, or TXT.', eyebrow:'LETTER WRITER', primaryIntent:'Write a letter online', kind:'creator', cluster:'Document Creator', priority:'P2', stage:'Research First', secondaryKeywords:['letter writer online','write letter online','letter maker'], input:['Form fields'], output:['DOCX','PDF','TXT'], processor:'creator-studio', launchState:'live', indexable:true },
  { id:'invoice-maker', route:'/invoice-maker', name:'Invoice Maker', title:'Invoice Maker – Create an Invoice Online', description:'Create an itemized invoice with automatic subtotal, tax, and total calculations, then export it as DOCX, PDF, or TXT.', eyebrow:'INVOICE MAKER', primaryIntent:'Create an invoice online', kind:'creator', cluster:'Document Creator', priority:'P2', stage:'Research First', secondaryKeywords:['invoice generator','free invoice maker','create invoice online'], input:['Form fields','Line items'], output:['DOCX','PDF','TXT'], processor:'creator-studio', launchState:'live', indexable:true },
  { id:'agenda-maker', route:'/agenda-maker', name:'Agenda Maker', title:'Agenda Maker – Create a Meeting Agenda Online', description:'Build a meeting agenda with objectives, attendees, timed topics, owners, and downloadable document formats.', eyebrow:'AGENDA MAKER', primaryIntent:'Create a meeting agenda', kind:'creator', cluster:'Document Creator', priority:'P2', stage:'Research First', secondaryKeywords:['meeting agenda maker','agenda template online','create agenda'], input:['Form fields','Agenda items'], output:['DOCX','PDF','TXT'], processor:'creator-studio', launchState:'live', indexable:true },
  { id:'meeting-minutes-maker', route:'/meeting-minutes-maker', name:'Meeting Minutes Maker', title:'Meeting Minutes Maker – Create Meeting Minutes Online', description:'Organize meeting notes, decisions, and action items into structured minutes with DOCX, PDF, or TXT export.', eyebrow:'MEETING MINUTES', primaryIntent:'Create meeting minutes', kind:'creator', cluster:'Document Creator', priority:'P2', stage:'Research First', secondaryKeywords:['meeting minutes template','minutes maker','create meeting minutes'], input:['Form fields','Action items'], output:['DOCX','PDF','TXT'], processor:'creator-studio', launchState:'live', indexable:true },
  { id:'checklist-maker', route:'/checklist-maker', name:'Checklist Maker', title:'Checklist Maker – Create a Checklist Online', description:'Turn one-item-per-line text into a clean printable checklist and export it as DOCX, PDF, or TXT.', eyebrow:'CHECKLIST MAKER', primaryIntent:'Create a checklist online', kind:'creator', cluster:'Document Creator', priority:'P2', stage:'Research First', secondaryKeywords:['checklist creator','make checklist online','printable checklist maker'], input:['Checklist items'], output:['DOCX','PDF','TXT'], processor:'creator-studio', launchState:'live', indexable:true },
  { id:'proposal-maker', route:'/proposal-maker', name:'Proposal Maker', title:'Proposal Maker – Create a Proposal Online', description:'Create a professional proposal with summary, scope, deliverables, timeline, pricing, terms, and next steps.', eyebrow:'PROPOSAL MAKER', primaryIntent:'Create a proposal online', kind:'creator', cluster:'Document Creator', priority:'P2', stage:'Research First', secondaryKeywords:['proposal generator','business proposal maker','proposal template online'], input:['Form fields'], output:['DOCX','PDF','TXT'], processor:'creator-studio', launchState:'live', indexable:true },
  { id:'business-plan-maker', route:'/business-plan-maker', name:'Business Plan Maker', title:'Business Plan Maker – Create a Business Plan Online', description:'Organize a practical business plan into standard sections and export the result as DOCX, PDF, or TXT.', eyebrow:'BUSINESS PLAN MAKER', primaryIntent:'Create a business plan online', kind:'creator', cluster:'Document Creator', priority:'P3', stage:'Research First', secondaryKeywords:['business plan builder','business plan template online','create business plan'], input:['Form fields'], output:['DOCX','PDF','TXT'], processor:'creator-studio', launchState:'live', indexable:true },
  { id:'memo-maker', route:'/memo-maker', name:'Memo Maker', title:'Memo Maker – Create a Professional Memo Online', description:'Create a concise professional memo with recipient, sender, subject, summary, details, and action required.', eyebrow:'MEMO MAKER', primaryIntent:'Create a memo online', kind:'creator', cluster:'Document Creator', priority:'P3', stage:'Research First', secondaryKeywords:['memo generator','memo template online','make a memo'], input:['Form fields'], output:['DOCX','PDF','TXT'], processor:'creator-studio', launchState:'live', indexable:true },
];
