import type { PlatformToolDefinition } from './catalog';

export const liveDocumentFormatTools: readonly PlatformToolDefinition[] = [
  {
    id: 'txt-to-pdf',
    route: '/txt-to-pdf',
    name: 'TXT to PDF',
    title: 'TXT to PDF – Convert Text File to PDF Online',
    description: 'Convert a plain TXT file to PDF in your browser while preserving line breaks and readable spacing. Choose A4 or US Letter and portrait or landscape pages.',
    eyebrow: 'TXT TO PDF',
    primaryIntent: 'Convert a TXT text file to PDF',
    kind: 'converter',
    cluster: 'Converter',
    priority: 'P2',
    stage: 'After Core',
    secondaryKeywords: ['convert txt to pdf', 'text file to pdf', 'txt file to pdf converter', 'text to pdf'],
    input: ['txt'],
    output: ['pdf'],
    processor: 'simpleDocumentToPdfProcessor',
    launchState: 'live',
    indexable: true,
  },
  {
    id: 'rtf-to-pdf',
    route: '/rtf-to-pdf',
    name: 'RTF to PDF',
    title: 'RTF to PDF – Convert Rich Text to PDF Online',
    description: 'Convert an RTF rich-text document to PDF in your browser using the platform’s existing RTF parser and browser PDF renderer.',
    eyebrow: 'RTF TO PDF',
    primaryIntent: 'Convert an RTF document to PDF',
    kind: 'converter',
    cluster: 'Converter',
    priority: 'P2',
    stage: 'After Core',
    secondaryKeywords: ['convert rtf to pdf', 'rich text to pdf', 'rtf file to pdf', 'rtf converter'],
    input: ['rtf'],
    output: ['pdf'],
    processor: 'simpleDocumentToPdfProcessor',
    launchState: 'live',
    indexable: true,
  },
  {
    id: 'document-viewer',
    route: '/document-viewer',
    name: 'Document Viewer',
    title: 'Document Viewer – View Documents Online Free',
    description: 'Open common document formats in one read-only browser viewer, including DOCX, PDF, TXT, HTML, RTF, JPG, PNG, CSV, and XLSX files.',
    eyebrow: 'DOCUMENT VIEWER',
    primaryIntent: 'Open and view common document formats online',
    kind: 'viewer',
    cluster: 'Viewer',
    priority: 'P1',
    stage: 'After Core',
    secondaryKeywords: ['document viewer online', 'view document online', 'online document reader', 'file viewer online'],
    input: ['docx', 'pdf', 'txt', 'html', 'rtf', 'jpg', 'jpeg', 'png', 'csv', 'xlsx'],
    output: ['preview'],
    launchState: 'live',
    indexable: true,
  },
];
