import type { PlatformToolDefinition } from './catalog';

export const livePdfTools: readonly PlatformToolDefinition[] = [
  {
    id: 'pdf-to-word',
    route: '/pdf-to-word',
    name: 'PDF to Word',
    title: 'PDF to Word – Free Online Converter',
    description: 'Convert a text-based PDF to an editable DOCX Word document in your browser. The converter extracts readable text, keeps page breaks, and creates a downloadable Word file.',
    eyebrow: 'PDF TO WORD',
    primaryIntent: 'Convert a PDF document to an editable Word DOCX file',
    kind: 'converter',
    cluster: 'PDF',
    priority: 'P0',
    stage: 'Now',
    secondaryKeywords: ['convert pdf to word', 'pdf to word converter', 'pdf to docx', 'convert pdf to docx'],
    input: ['pdf'],
    output: ['docx'],
    processor: 'pdfToWordProcessor',
    launchState: 'live',
    indexable: true,
  },
  {
    id: 'compress-pdf',
    route: '/compress-pdf',
    name: 'Compress PDF',
    title: 'Compress PDF – Reduce PDF File Size Online',
    description: 'Compress PDF files directly in your browser with QPDF-based stream and object compression, then download the smaller PDF when size reduction is possible.',
    eyebrow: 'COMPRESS PDF',
    primaryIntent: 'Reduce PDF file size',
    kind: 'pdf',
    cluster: 'PDF',
    priority: 'P1',
    stage: 'PDF Expansion',
    secondaryKeywords: ['pdf compressor', 'compress pdf online', 'reduce pdf size', 'reduce pdf file size'],
    input: ['pdf'],
    output: ['pdf'],
    processor: 'pdfCompressorProcessor',
    launchState: 'live',
    indexable: true,
  },
  {
    id: 'merge-pdf',
    route: '/merge-pdf',
    name: 'Merge PDF',
    title: 'Merge PDF – Combine PDF Files Online',
    description: 'Combine two or more PDF files into one PDF in the order you choose. Processing runs in the browser and the merged file downloads immediately.',
    eyebrow: 'MERGE PDF',
    primaryIntent: 'Combine multiple PDF files into one PDF',
    kind: 'pdf',
    cluster: 'PDF',
    priority: 'P1',
    stage: 'PDF Expansion',
    secondaryKeywords: ['combine pdf', 'merge pdf files', 'combine pdf files', 'pdf merger'],
    input: ['pdf', 'pdf+'],
    output: ['pdf'],
    processor: 'pdfMergeProcessor',
    launchState: 'live',
    indexable: true,
  },
  {
    id: 'split-pdf',
    route: '/split-pdf',
    name: 'Split PDF',
    title: 'Split PDF – Separate PDF Pages Online',
    description: 'Split a PDF by selected pages or separate every page into its own PDF. The browser creates the selected output without uploading the source to an account.',
    eyebrow: 'SPLIT PDF',
    primaryIntent: 'Split or extract pages from a PDF',
    kind: 'pdf',
    cluster: 'PDF',
    priority: 'P1',
    stage: 'PDF Expansion',
    secondaryKeywords: ['pdf splitter', 'split pdf pages', 'separate pdf pages', 'extract pdf pages'],
    input: ['pdf'],
    output: ['pdf', 'pdf+'],
    processor: 'pdfSplitProcessor',
    launchState: 'live',
    indexable: true,
  },
  {
    id: 'pdf-ocr',
    route: '/pdf-ocr',
    name: 'PDF OCR',
    title: 'PDF OCR – Make Scanned PDFs Searchable',
    description: 'Run OCR on scanned PDF pages in your browser, extract recognized text, and create a searchable PDF when possible.',
    eyebrow: 'PDF OCR',
    primaryIntent: 'Recognize text in scanned PDFs and create a searchable PDF',
    kind: 'ocr',
    cluster: 'PDF',
    priority: 'P2',
    stage: 'PDF Expansion',
    secondaryKeywords: ['ocr pdf', 'pdf ocr online', 'searchable pdf', 'recognize text in pdf'],
    input: ['pdf'],
    output: ['searchable-pdf', 'text'],
    processor: 'pdfOcrProcessor',
    launchState: 'live',
    indexable: true,
  },
  {
    id: 'pdf-reader',
    route: '/pdf-reader',
    name: 'PDF Reader',
    title: 'PDF Reader – Read PDF Online Free',
    description: 'Open and read PDF files directly in your browser with page navigation and zoom controls. View PDF pages online without changing the original file.',
    eyebrow: 'PDF READER',
    primaryIntent: 'Read and view PDF documents online',
    kind: 'viewer',
    cluster: 'PDF',
    priority: 'P2',
    stage: 'PDF Expansion',
    secondaryKeywords: ['read pdf online', 'pdf reader online', 'view pdf online', 'online pdf viewer'],
    input: ['pdf'],
    output: ['preview'],
    launchState: 'live',
    indexable: true,
  },
  {
    id: 'pdf-to-jpg',
    route: '/pdf-to-jpg',
    name: 'PDF to JPG',
    title: 'PDF to JPG – Convert PDF Pages to Images',
    description: 'Convert PDF pages to JPG images in your browser. Choose specific pages, control JPG quality and resolution, and download one image or a ZIP of multiple pages.',
    eyebrow: 'PDF TO JPG',
    primaryIntent: 'Convert PDF pages to JPG images',
    kind: 'converter',
    cluster: 'PDF',
    priority: 'P1',
    stage: 'PDF Expansion',
    secondaryKeywords: ['convert pdf to jpg', 'pdf to image', 'pdf to jpeg', 'pdf to jpg converter'],
    input: ['pdf'],
    output: ['jpg', 'zip'],
    processor: 'pdfToJpgProcessor',
    launchState: 'live',
    indexable: true,
  },
];
