import type { PlatformToolDefinition } from './catalog';

export const livePdfMarkupTools: readonly PlatformToolDefinition[] = [
  {
    id: 'edit-pdf',
    route: '/edit-pdf',
    name: 'Edit PDF',
    title: 'Edit PDF – Free Online PDF Editor',
    description: 'Edit PDF pages directly in your browser by adding text, highlights, and rectangle overlays, then download a new edited copy.',
    eyebrow: 'EDIT PDF',
    primaryIntent: 'Edit a PDF online',
    kind: 'pdf',
    cluster: 'PDF',
    priority: 'P1',
    stage: 'PDF Expansion',
    secondaryKeywords: ['pdf editor online free', 'free pdf editor online', 'online pdf editor', 'edit pdf online'],
    input: ['pdf'],
    output: ['pdf'],
    processor: 'pdfEditorProcessor',
    launchState: 'live',
    indexable: true,
  },
  {
    id: 'pdf-annotator',
    route: '/pdf-annotator',
    name: 'PDF Annotator',
    title: 'PDF Annotator – Annotate PDF Online',
    description: 'Annotate PDF pages in your browser with highlights, text notes, and boxes, then export a separate marked-up PDF.',
    eyebrow: 'PDF ANNOTATOR',
    primaryIntent: 'Annotate and mark up a PDF online',
    kind: 'pdf',
    cluster: 'PDF',
    priority: 'P2',
    stage: 'PDF Expansion',
    secondaryKeywords: ['annotate pdf', 'pdf annotator online', 'mark up pdf', 'annotate pdf online'],
    input: ['pdf'],
    output: ['pdf'],
    processor: 'pdfEditorProcessor',
    launchState: 'live',
    indexable: true,
  },
];
