import type { PlatformToolDefinition } from './catalog';

export const liveUniversalConverterTools: readonly PlatformToolDefinition[] = [
  {
    id: 'document-converter',
    route: '/document-converter',
    name: 'Document Converter',
    title: 'Document Converter – Convert Documents Online Free',
    description: 'Convert PDF, Word DOCX, JPG, PNG, HTML, Excel XLSX, and CSV files using one browser-based document converter.',
    eyebrow: 'DOCUMENT CONVERTER',
    primaryIntent: 'Convert documents between supported formats',
    kind: 'converter',
    cluster: 'Converter',
    priority: 'P1',
    stage: 'Next',
    secondaryKeywords: ['doc converter', 'word converter', 'docx converter', 'online document converter', 'file converter'],
    input: ['pdf', 'docx', 'jpg', 'jpeg', 'png', 'html', 'xlsx', 'csv'],
    output: ['pdf', 'docx', 'jpg'],
    processor: 'universalConverterDispatcher',
    launchState: 'live',
    indexable: true,
  },
  {
    id: 'pdf-converter',
    route: '/pdf-converter',
    name: 'PDF Converter',
    title: 'PDF Converter – Convert Files to and from PDF',
    description: 'Convert Word DOCX, JPG, PNG, HTML, Excel XLSX, and CSV files to PDF, or convert PDF files to Word DOCX and JPG images.',
    eyebrow: 'PDF CONVERTER',
    primaryIntent: 'Convert files to and from PDF',
    kind: 'converter',
    cluster: 'PDF',
    priority: 'P1',
    stage: 'PDF Expansion',
    secondaryKeywords: ['pdf converter', 'free pdf converter', 'convert to pdf', 'convert pdf', 'document to pdf'],
    input: ['pdf', 'docx', 'jpg', 'jpeg', 'png', 'html', 'xlsx', 'csv'],
    output: ['pdf', 'docx', 'jpg'],
    processor: 'universalConverterDispatcher',
    launchState: 'live',
    indexable: true,
  },
];
