import type { DocumentProcessor, DocumentRegistry } from '../../../core/document-engine/registry/documentRegistry';
import type { File } from '../../../core/document-engine/types/File';
import type { HtmlToDocxResult } from './HtmlToDocxResult';
import { asOutput, caught, failed, outputName, readFile, sourceOf, wordWarning } from '../shared';
import { validateHtml, validateHtmlFile } from '../shared';

type DocxApi = typeof import('docx');
function sanitize(html: string): { root: HTMLElement; warnings: ReturnType<typeof wordWarning>[] } { const template = document.createElement('template'); template.innerHTML = html; const warnings: ReturnType<typeof wordWarning>[] = []; const removed = template.content.querySelectorAll('script,style,iframe,object,embed,form,input,button,textarea,select,meta,link,base,svg,video,audio').length; template.content.querySelectorAll('script,style,iframe,object,embed,form,input,button,textarea,select,meta,link,base,svg,video,audio').forEach((node) => node.remove()); template.content.querySelectorAll<HTMLElement>('*').forEach((element) => Array.from(element.attributes).forEach((attribute) => { const name = attribute.name.toLowerCase(); const value = attribute.value.trim(); if (name.startsWith('on') || name === 'srcdoc' || name === 'formaction') element.removeAttribute(attribute.name); if (name === 'href' && !/^(https?:|mailto:)/i.test(value)) element.removeAttribute(attribute.name); if (name === 'src' && !/^data:image\/(?:png|jpe?g|gif|webp);base64,/i.test(value)) element.removeAttribute(attribute.name); })); if (removed) warnings.push(wordWarning('UNSAFE_MARKUP_REMOVED', 'Scripts, styles, active content, and unsafe media were removed.')); const root = document.createElement('div'); root.append(...Array.from(template.content.childNodes)); return { root, warnings }; }
function imageRun(api: DocxApi, source: string): any | null { const match = /^data:image\/(png|jpe?g|gif);base64,(.+)$/i.exec(source); if (!match) return null; try { const binary = atob(match[2]); const data = Uint8Array.from(binary, (character) => character.charCodeAt(0)); const type = match[1].toLowerCase() === 'jpeg' ? 'jpg' : match[1].toLowerCase(); return new api.ImageRun({ data, type, transformation: { width: 600, height: 400 } } as any); } catch { return null; } }
function runs(api: DocxApi, node: Node, bold = false, italic = false, warnings?: ReturnType<typeof wordWarning>): any[] { if (node.nodeType === Node.TEXT_NODE) return node.textContent ? [new api.TextRun({ text: node.textContent, bold, italics: italic })] : []; if (node.nodeType !== Node.ELEMENT_NODE) return []; const element = node as HTMLElement; if (element.tagName === 'IMG') { const run = imageRun(api, element.getAttribute('src') ?? ''); if (run) return [run]; if (warnings) warnings.message = 'Unsupported or remote images were omitted.'; return []; } const nextBold = bold || ['B', 'STRONG'].includes(element.tagName); const nextItalic = italic || ['I', 'EM'].includes(element.tagName); return Array.from(element.childNodes).flatMap((child) => runs(api, child, nextBold, nextItalic, warnings)); }
function alignment(api: DocxApi, element: HTMLElement): any { const value = element.getAttribute('align') ?? element.style.textAlign; return value === 'center' ? api.AlignmentType.CENTER : value === 'right' ? api.AlignmentType.RIGHT : value === 'justify' ? api.AlignmentType.JUSTIFIED : undefined; }
async function childrenFor(api: DocxApi, root: HTMLElement, warnings: ReturnType<typeof wordWarning>): Promise<any[]> { const children: any[] = []; const blocks = 'H1,H2,H3,H4,H5,H6,P,DIV,LI,PRE,QUOTE'; const visit = (element: HTMLElement, list?: 'number' | 'bullet') => { if (element.matches('TABLE')) { const rows = Array.from(element.querySelectorAll(':scope > tbody > tr, :scope > tr')).map((row) => new api.TableRow({ children: Array.from(row.children).map((cell) => new api.TableCell({ children: [new api.Paragraph({ children: runs(api, cell, false, false, warnings) })] })) })); if (rows.length) children.push(new api.Table({ rows })); return; } if (element.matches('UL,OL')) { const type = element.tagName === 'OL' ? 'number' : 'bullet'; Array.from(element.children).forEach((child) => visit(child as HTMLElement, type)); return; } if (element.matches(blocks)) { const level = /^H([1-6])$/.exec(element.tagName); const paragraph: Record<string, unknown> = { children: runs(api, element, false, false, warnings), alignment: alignment(api, element) }; if (level) paragraph.heading = api.HeadingLevel[`HEADING_${level[1]}` as keyof typeof api.HeadingLevel]; if (list) paragraph.numbering = { reference: list === 'number' ? 'html-numbered' : 'html-bulleted', level: 0 }; children.push(new api.Paragraph(paragraph)); return; } Array.from(element.children).forEach((child) => visit(child as HTMLElement, list)); }; Array.from(root.children).forEach((element) => visit(element as HTMLElement)); return children; }
export class HtmlToDocxProcessor implements DocumentProcessor<HtmlToDocxResult> { type = 'html' as const; async process(input: File | readonly File[] | string, rawOptions: Record<string, unknown> = {}): Promise<HtmlToDocxResult> { if (typeof input !== 'string' && !('size' in input)) return failed({ name: '', size: 0 }, 'HTML_INPUT_REQUIRED', 'HTML or a single HTML file is required'); const file = typeof input === 'string' ? { name: 'document.html', size: new TextEncoder().encode(input).byteLength, type: 'text/html' } : input; const source = sourceOf(file); try { let html = typeof input === 'string' ? input : ''; if (typeof input !== 'string') { const invalid = validateHtmlFile(input); if (invalid.length) return failed(source, 'INVALID_HTML', invalid.join('. ')); html = new TextDecoder().decode(await readFile(input)); } const invalid = validateHtml(html); if (invalid.length) return failed(source, 'EMPTY_HTML', invalid[0]); const sanitized = sanitize(html); const api = await import('docx'); const warningState = wordWarning('UNSUPPORTED_FEATURE', ''); const children = await childrenFor(api, sanitized.root, warningState); if (!children.length) return failed(source, 'EMPTY_HTML', 'HTML contains no supported printable content', sanitized.warnings); const doc = new api.Document({ numbering: { config: [{ reference: 'html-bulleted', levels: [{ level: 0, format: api.LevelFormat.BULLET, text: '\\u2022', alignment: api.AlignmentType.LEFT }] }, { reference: 'html-numbered', levels: [{ level: 0, format: api.LevelFormat.DECIMAL, text: '%1.', alignment: api.AlignmentType.LEFT }] }] }, sections: [{ properties: {}, children }] }); const blob = await api.Packer.toBlob(doc); const warnings = sanitized.warnings.concat(warningState.message ? [warningState] : []); const options = rawOptions as { filename?: string }; return { success: true, source, outputSize: blob.size, output: asOutput(outputName(file.name, 'docx', options.filename), blob, 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', { paragraphCount: children.length }), warnings, errors: [], metadata: { paragraphCount: children.length } }; } catch (error) { return caught(source, 'HTML_TO_DOCX_FAILED', error); } } }
export const htmlToDocxProcessor = new HtmlToDocxProcessor();
export function registerHtmlToDocxProcessor(registry: DocumentRegistry): HtmlToDocxProcessor { if (!registry.getAll(htmlToDocxProcessor.type).includes(htmlToDocxProcessor)) registry.register(htmlToDocxProcessor); return htmlToDocxProcessor; }
